CREATE TABLE customer(
                         id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         first_name varchar(255) NOT NULL,
                         last_name varchar(255) NOT NULL,
                         email varchar(255) UNIQUE,
                         address varchar(255) NOT NULL
)