create table customer(
                         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         first_name varchar(100) NOT NULL,
                         last_name varchar(100) NOT NULL,
                         email varchar UNIQUE,
                         address varchar NOT NULL
)